### ISSUE TITLE
Tooltip on the search box blocks selecting the first item after it filters

### ISSUE THREAD

**Issue by joshtransient** [s-KaiNet/sp-rest-explorer#2]
Could you drop the tooltip in favor of just showing it on the page, or drawing it to the right of the search box instead? This is just an annoyance, not a bug or anything, just frustrating when I know the endpoint or type I'm looking for and I have to wiggle the mouse a bunch to get the tooltip out of the way.

**Comment by s-KaiNet** [comment]
Valid, pushed an update, it might take a while when the changes will be available.
