### ISSUE TITLE
Feature request : export as typescript

### ISSUE THREAD

**Issue by stevebeauge** [s-KaiNet/sp-rest-explorer#3]
This tools is awesome, mainly because Microsoft has a quite poor documentation regarding the REST APIs.

It would be nice, in each type page to have a typescript type snippet that we may copy/paste into SPFX project, when we have to deal with some spHttpClient request.

For example, in the page [SP.Web entity page](https://s-kainet.github.io/sp-rest-explorer/#/entity/SP.Web), it would be nice to have a block containing something like:

````typescript
interface SP_Web extends SP_SecurableObject {
    AccessRequestListUrl: string,
    AccessRequestSiteDescription: string
    // and so on ...
}
````

Another project [edmx-typescript-generator](https://github.com/izatop/edmx-typescript-generator) is doing something similar, but it's for command line and there are some types that are not properly exported.

**Comment by s-KaiNet** [comment]
Yeah, it makes sense, thanks for the suggestion! Will work on this feature when I finish upcoming fast-serve changes.

**Comment by s-KaiNet** [comment]
Will close this one, because currently I don't have time to invest in new features for this project.
