### ISSUE TITLE
App is broken?

### ISSUE THREAD

**Issue by stevebeauge** [s-KaiNet/sp-rest-explorer#4]
Today, I tried to use the application but it does not work.

The page loads, the header is present but the main section of the page only contains the spinner

![image](https://github.com/user-attachments/assets/b5d734ef-f45c-46ec-b1ef-7f8935d47695)

Tried on FF, Edge on multiple computers, same result.

If it can help, here's the browser console output:

![image](https://github.com/user-attachments/assets/d0713250-d8f3-48b5-8b87-91408822a261)

thanks

**Comment by s-KaiNet** [comment]
yeah... seems azure functions stopped working starting 1st of November... will take a look.

**Comment by s-KaiNet** [comment]
Fixed, the source tenant where the data was collected, was removed, thus everything stopped working. But I have to change auth method as well, because `sp-request` is deprecated.

**Comment by stevebeauge** [comment]
Thanks for your quick resolution.

This tool is awesome and helped me a lot to discover and understand some SP internals!
