### ISSUE TITLE
Sidebars for "Explore API" and "Explore Types" do not load

### ISSUE THREAD

**Issue by influential-eliot** [s-KaiNet/sp-rest-explorer#6]
Looks like a repeat of #5 / #4 perhaps? Same issue?

Not going to give logs unless it's really needed. :)

---

@joshtransient / @stevebeauge ... you seeing it?

**Comment by s-KaiNet** [comment]
I found the reason - this url `https://sprestapiexplorer.blob.core.windows.net/api-files/metadata.latest.zip.json` doesn't return data because the file is not available. IDK why, will take a look in the evening.

**Comment by s-KaiNet** [comment]
Maybe it's good time to learn new react 19 features and do a full re-write the UI in react?) I don't use Vue any more.

**Comment by s-KaiNet** [comment]
Could you check if it's fixed now?

**Comment by stevebeauge** [comment]
It's ok on my side

thanks

**Comment by influential-eliot** [comment]
Looks good, @s-KaiNet !
![image](https://github.com/user-attachments/assets/0fe65c08-844c-4472-a12b-1e5055b63e0a)
Loving your dev story mapped out in this issue! 😅

**Comment by influential-eliot** [comment]
Sorry, yes ... complete!
